### ISSUE TITLE
v0.3.11 error win32 x64

### ISSUE THREAD

**Issue by Dbcurtis** [microsoft/vscode-java-installer#132] opened 2021-01-26 00:53 UTC
:warning:Please attach **%TEMP%\vscode-java-installer\log.txt** and **%TEMP%\vscode-java-installer\AdoptOpenJDK-MSI.log** for more details.

version: 0.3.11
env:
```
JAVA_HOME: undefined
PATH:
C:\Program Files\Mozilla Firefox
C:\Program Files\Python38\Scripts\
C:\Program Files\Python38\
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\dotnet\
C:\Program Files\PuTTY\
C:\Program Files\Git\cmd
C:\Users\Dan\AppData\Local\Microsoft\WindowsApps
C:\Users\Dan\AppData\Local\Programs\Microsoft VS Code\bin
C:\Users\Dan\AppData\Roaming\Python\Python38\Scripts
C:\Users\Dan\AppData\Local\Programs\Microsoft VS Code Insiders\bin
C:\Users\Dan\AppData\Local\GitHubDesktop\bin
JDKs:
C:\Program Files\Java\jdk1.8.0_231	WindowsRegistry,WindowsRegistry,DefaultLocation
```
log:
```
[3:31:25 PM] AdoptOpenJDK-11-x64
[4:39:11 PM] Download JDK ... [Completed]
[4:39:11 PM] Install JDK
[4:39:11 PM] Installing AdoptOpenJDK-11-x64...
[4:39:33 PM] Error occurred
[4:39:33 PM] Error: Command failed with exit code 1603: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\Dan\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.10_9.msi" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v "C:\Users\Dan\AppData\Local\Temp\vscode-java-installer\AdoptOpenJDK-MSI.log"

```
[log.txt](https://github.com/microsoft/vscode-java-installer/files/5870462/log.txt)
[AdoptOpenJDK-MSI.log](https://github.com/microsoft/vscode-java-installer/files/5870469/AdoptOpenJDK-MSI.log)

**Comment by Eskibear** [comment] 2021-01-26 01:58
Thank you for detailed logs. Installation of JDK 11 failed. We'll forward them to AdoptOpenJDK team. 

VS Code Java requires JDK 11+ to launch itself. For the moment since the installation of OpenJDK 11 failed, you might want to download and install one by your own, and re-run our installer.

**Comment by Eskibear** [comment] 2021-01-26 02:02
> [4:39:33 PM] Error: Command failed with exit code 1603: C:\WINDOWS\System32\msiexec.exe /i "C:\Users\Dan\AppData\Local\Temp\vscode-java-installer\binaries\jdk\11\x64\OpenJDK11U-jdk_x64_windows_hotspot_11.0.10_9.msi" MSIINSTALLPERUSER=1 ADDLOCAL=FeatureJavaHome,FeatureEnvironment,FeatureJarFileRunWith /passive /l*v "C:\Users\Dan\AppData\Local\Temp\vscode-java-installer\AdoptOpenJDK-MSI.log"
> 
> 
> [log.txt](https://github.com/microsoft/vscode-java-installer/files/5870462/log.txt)
> [AdoptOpenJDK-MSI.log](https://github.com/microsoft/vscode-java-installer/files/5870469/AdoptOpenJDK-MSI.log)

@douph1  Another MSI 1603 issue with, can you take a look at the AdoptOpenJDK-MSI.log above?

**Comment by Dbcurtis** [comment] 2021-01-26 07:15
Problem solved, was running java8.
updated and problem solved
Thanks

**Comment by douph1** [comment] 2021-01-26 07:40
>RunEngine wait timed out
>Install server not responding

can't say more, maybe slow down due to AV scanning or Installer busy .. maybe need to check Event Log

**Comment by Eskibear** [comment] 2021-01-26 08:53
@douph1 Thank you for the quick response, and I'll let you know if more detailed error logs are collected from users. 😉 

@Dbcurtis Good to know it works. I'm closing this issue for the moment as we don't find clear clues or stable ways to reproduce it.

**Closed as completed by Eskibear** 2021-01-26 08:53 UTC
